[package]
name = "test"
version = "0.1.0"
authors = ["robinson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test"
path = "src/test.rs"
doc = false

[dependencies]
#encoding_rs = "0.8.14"
lazy_static = "1.4.0"